CREATE TABLE customers (
    "customerID" TEXT,
    gender TEXT,
    "SeniorCitizen" TEXT,
    "Partner" TEXT,
    "Dependents" TEXT,
    tenure INT,
    "PhoneService" TEXT,
    "MultipleLines" TEXT,
    "InternetService" TEXT,
    "OnlineSecurity" TEXT,
    "OnlineBackup" TEXT,
    "DeviceProtection" TEXT,
    "TechSupport" TEXT,
    "StreamingTV" TEXT,
    "StreamingMovies" TEXT,
    "Contract" TEXT,
    "PaperlessBilling" TEXT,
    "PaymentMethod" TEXT,
    "MonthlyCharges" NUMERIC,
    "TotalCharges" NUMERIC,
    "Churn" TEXT,
    "TenureBucket" TEXT,
    "ChargeBucket" TEXT,
    "ChurnFlag" INT,
    "PredictedChurnProb" NUMERIC
);